/* eslint-disable import/prefer-default-export */
const SITE_URL = new URL(`https://${process.env.NEXT_PUBLIC_HOSTNAME || 'https://www.aroconnection.com'}`);

// generated by strapi
const COMPONENT_KEY = '__component';

export {
  COMPONENT_KEY,
  SITE_URL,
};
